apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: messaging-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-app-service
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: django-app-service
            port:
              number: 80
      - path: /admin/
        pathType: Prefix
        backend:
          service:
            name: django-app-service
            port:
              number: 80
      - path: /static/
        pathType: Prefix
        backend:
          service:
            name: django-app-service
            port:
              number: 80
  # Optional: Add TLS configuration if you have SSL certificates
  # tls:
  # - hosts:
  #   - messaging-app.local
  #   secretName: messaging-app-tls