# Check if file exists
if [ -f "messaging_app/ingress.yaml" ]; then
    echo "File exists"
    
    # Check if file is not empty
    if [ -s "messaging_app/ingress.yaml" ]; then
        echo "File is not empty"
        exit 0  # Success - file exists and is not empty
    else
        echo "File exists but is empty"
        exit 1  # Failure - file exists but empty
    fi
else
    echo "File does not exist"
    exit 1  # Failure - file doesn't exist
fi